<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CADR.Common.Mvc</RootNamespace>
    <AssemblyName>CADR.Common.Mvc</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="AutoMapper.Extensions.EnumMapping" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CADR.Common.Core.Contracts\CADR.Common.Core.Contracts.csproj" />
  </ItemGroup>

</Project>
