<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CADR.Portal.Tests</RootNamespace>
    <AssemblyName>CADR.Portal.Tests</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="AutoMapper.Extensions.EnumMapping" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CADR.Portal\CADR.Portal.csproj" />
  </ItemGroup>

</Project>
