// <auto-generated />
using System;
using CADR.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CADR.Context.Migrations
{
    [DbContext(typeof(CadrContext))]
    partial class CadrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CADR.Administrations.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameLowerCase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NameLowerCase" }, "IX_Organization_NameLowerCase")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("CADR.Administrations.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_RefreshToken_UserId")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("CADR.Administrations.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailLowerCase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoginLowerCase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmailLowerCase" }, "IX_User_EmailLowerCase")
                        .IsUnique()
                        .HasFilter("\"EmailConfirmed\" is TRUE AND \"DeletedAt\" IS NULL");

                    b.HasIndex(new[] { "LoginLowerCase" }, "IX_User_LoginLowerCase")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CADR.Administrations.Entities.UserInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInvites", (string)null);
                });

            modelBuilder.Entity("CADR.Administrations.Entities.UserOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex(new[] { "UserId", "OrganizationId" }, "IX_UserOrganization_User")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("UserOrganizations", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.Adr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdrFolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentAdrFolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdrFolderId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentAdrFolderId");

                    b.HasIndex("TemplateId");

                    b.HasIndex(new[] { "OrganizationId", "Number" }, "IX_Adr_Number")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex(new[] { "OrganizationId", "ParentAdrFolderId" }, "IX_Adr_ParentAdrFolder")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex(new[] { "OrganizationId", "Status" }, "IX_Adr_Status")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Adrs", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdrId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "AdrId", "CreatedAt" }, "IX_AdrComment_CreatedAt")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("AdrComments", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentAdrFolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentAdrFolderId");

                    b.HasIndex(new[] { "OrganizationId", "ParentAdrFolderId", "Name" }, "IX_AdrFolder_Name")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("AdrFolders", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceAdrId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAdrId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TargetAdrId");

                    b.HasIndex(new[] { "SourceAdrId", "TargetAdrId", "Type" }, "IX_AdrLink_Type")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("AdrLinks", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrOrganizationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikesRequiredForApproval")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AdrOrganizationSettings", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdrId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AdrId", "Position" }, "IX_AdrSection_Position")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("AdrSections", (string)null);
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrganizationId", "Name" }, "IX_AdrTemplate_Name")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL AND \"OrganizationId\" IS NOT NULL");

                    b.ToTable("AdrTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe644bbb-416f-4af0-abc0-5e0144db26c0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Name = "Минимальный",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Name = "Базовый",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrTemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TemplateId", "Position" }, "IX_AdrTemplateSection_Position")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("AdrTemplateSections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6503c25-bb02-4b3b-82b4-abe7576c2581"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Что заставило меня принять такое решение?",
                            Placeholder = "Опишите контекст и суть проблемы — например, в свободной форме (двумя-тремя предложениями) или в виде наглядной истории.Можно сформулировать проблему как вопрос. Рекомендуется добавить ссылки на доски для совместной работы или системы управления задачами.Четко обозначьте область действия принимаемого решения, например, выделив или указав конкретные элементы архитектуры (компоненты, коннекторы и т. д.).",
                            Position = 1,
                            TemplateId = new Guid("fe644bbb-416f-4af0-abc0-5e0144db26c0"),
                            Title = "Контекст",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("0f1f1d4a-4898-4ee0-8ff2-ae34ab95ea6c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Решение и соответствующее обоснование",
                            Placeholder = "{название варианта 1}\r\n{название варианта 2}\r\n{название варианта 3}\r\n…",
                            Position = 2,
                            TemplateId = new Guid("fe644bbb-416f-4af0-abc0-5e0144db26c0"),
                            Title = "Решение",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("c9cbb06f-d455-4ef9-8435-8832fcbb66fd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "На что повлияет данное решение?",
                            Placeholder = "Выбранный вариант: «{название варианта 1}», поскольку {обоснование, например: единственный вариант, отвечающий решающему критерию | вариант, устраняющий воздействие {воздействие} | … | вариант, показавший наилучший результат}.\r\nПоследствия\r\nХорошие, потому что {положительные последствия, например, улучшение одного или нескольких желаемых качеств, …}\r\nПлохие, потому что {отрицательные последствия, например, ухудшение одного или нескольких желаемых качеств, …}\r\n…",
                            Position = 3,
                            TemplateId = new Guid("fe644bbb-416f-4af0-abc0-5e0144db26c0"),
                            Title = "Последствия",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("68d5fdba-fe6d-451c-bd18-bc64b3a180cf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Что заставило меня принять такое решение?",
                            Placeholder = "Опишите контекст и суть проблемы — например, в свободной форме (двумя-тремя предложениями) или в виде наглядной истории.Можно сформулировать проблему как вопрос. Рекомендуется добавить ссылки на доски для совместной работы или системы управления задачами.Четко обозначьте область действия принимаемого решения, например, выделив или указав конкретные элементы архитектуры (компоненты, коннекторы и т. д.).",
                            Position = 1,
                            TemplateId = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            Title = "Контекст",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("4b1e7519-e638-4d05-bec8-78342634e730"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Решение и соответствующее обоснование",
                            Placeholder = "{название варианта 1}\r\n{название варианта 2}\r\n{название варианта 3}\r\n…",
                            Position = 2,
                            TemplateId = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            Title = "Решение",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("ee962af1-c86b-45fe-ab22-4a8110a160f5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "На что повлияет данное решение?",
                            Placeholder = "Выбранный вариант: «{название варианта 1}», поскольку {обоснование, например: единственный вариант, отвечающий решающему критерию | вариант, устраняющий воздействие {воздействие} | … | вариант, показавший наилучший результат}.\r\nПоследствия\r\nХорошие, потому что {положительные последствия, например, улучшение одного или нескольких желаемых качеств, …}\r\nПлохие, потому что {отрицательные последствия, например, ухудшение одного или нескольких желаемых качеств, …}\r\n…",
                            Position = 3,
                            TemplateId = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            Title = "Последствия",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("d5b7e4b1-7032-4ce5-993a-2e8da86c5709"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Как я обеспечу соблюдение этого решения?",
                            Placeholder = "Чтобы убедиться, что решение «{название решения}» соблюдается на практике, мы будем\r\n{способ проверки, например: периодически проверять {что проверяем: процесс | документы | результат работы | …}\r\nв формате {вид проверки: аудит | контрольная точка | ревью артефактов | опрос участников | …}\r\n| отслеживать показатель «{метрика}» и сверять его с целевым значением {значение}\r\n| поручить {роль ответственного} проверять соответствие с периодичностью {периодичность: раз в месяц | каждую итерацию | ежеквартально | …}\r\n| …}.\r\n\r\nОтклонения от решения фиксируются {где фиксируются: в комментариях к этому ADR | в системе задач | в журнале проверок | …},\r\nпосле чего {что делаем дальше: проводится разбор с {роль, принимающая решение} | решение уточняется или отменяется через новое ADR | …}.",
                            Position = 4,
                            TemplateId = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            Title = "Соблюдение требований",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("500bf9b4-349b-490e-a475-49ba1da3bdc9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Перечислите все рассмотренные варианты",
                            Placeholder = "{название варианта 1}\r\n{пример | описание | ссылка на дополнительную информацию | …}\r\n\r\nХорошо, потому что {аргумент а}\r\nХорошо, потому что {аргумент б}\r\nНейтрально, потому что {аргумент в}\r\nПлохо, потому что {аргумент г}\r\n…\r\n\r\n{название другого варианта}\r\n{пример | описание | ссылка на дополнительную информацию | …}\r\n\r\nХорошо, потому что {аргумент а}\r\nНейтрально, потому что {аргумент б}\r\nПлохо, потому что {аргумент в}\r\n…",
                            Position = 5,
                            TemplateId = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            Title = "Плюсы и минусы вариантов",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        },
                        new
                        {
                            Id = new Guid("ec56b0ef-3a7d-44b0-a2ca-0b74e2f1023e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Hint = "Укажите всё, что усиливает доверие к решению и помогает в дальнейшем",
                            Placeholder = "{дополнительные доказательства или обоснование уверенности в принятом решении, например: результаты расчётов | прототип | обратная связь {от кого} | …}\r\n\r\n{договорённости команды, например: согласовано с {роль/участники} {дата} | решение принято консенсусом | …}\r\n\r\n{когда и как решение должно быть реализовано, например: внедряется начиная с {этап/дата} | ответственность за реализацию — {роль} | …}\r\n\r\n{условия пересмотра решения, например: пересматриваем, если {условие} | revisit {дата/событие} | …}\r\n\r\n{ссылки на другие решения и ресурсы, например: связанное ADR-{номер} | документация | исследование | …}",
                            Position = 6,
                            TemplateId = new Guid("94b3e49d-e314-4b0e-b620-35e38759feaa"),
                            Title = "Дополнительная информация",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system"
                        });
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdrId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AdrId", "UserId" }, "IX_AdrVote_User")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("AdrVotes", (string)null);
                });

            modelBuilder.Entity("CADR.Administrations.Entities.UserInvite", b =>
                {
                    b.HasOne("CADR.Administrations.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CADR.Administrations.Entities.User", "User")
                        .WithMany("Invites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CADR.Administrations.Entities.UserOrganization", b =>
                {
                    b.HasOne("CADR.Administrations.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CADR.Administrations.Entities.User", "User")
                        .WithMany("Organizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.Adr", b =>
                {
                    b.HasOne("CADR.Adrs.Entities.AdrFolder", null)
                        .WithMany("Adrs")
                        .HasForeignKey("AdrFolderId");

                    b.HasOne("CADR.Administrations.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CADR.Administrations.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CADR.Adrs.Entities.AdrFolder", "ParentAdrFolder")
                        .WithMany()
                        .HasForeignKey("ParentAdrFolderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CADR.Adrs.Entities.AdrTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Organization");

                    b.Navigation("ParentAdrFolder");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrComment", b =>
                {
                    b.HasOne("CADR.Adrs.Entities.Adr", "Adr")
                        .WithMany("Comments")
                        .HasForeignKey("AdrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CADR.Administrations.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adr");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrFolder", b =>
                {
                    b.HasOne("CADR.Administrations.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CADR.Adrs.Entities.AdrFolder", "ParentAdrFolder")
                        .WithMany("ChildFolder")
                        .HasForeignKey("ParentAdrFolderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organization");

                    b.Navigation("ParentAdrFolder");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrLink", b =>
                {
                    b.HasOne("CADR.Adrs.Entities.Adr", "SourceAdr")
                        .WithMany("SourceLinks")
                        .HasForeignKey("SourceAdrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CADR.Adrs.Entities.Adr", "TargetAdr")
                        .WithMany("TargetLinks")
                        .HasForeignKey("TargetAdrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceAdr");

                    b.Navigation("TargetAdr");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrOrganizationSettings", b =>
                {
                    b.HasOne("CADR.Administrations.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrSection", b =>
                {
                    b.HasOne("CADR.Adrs.Entities.Adr", "Adr")
                        .WithMany("Sections")
                        .HasForeignKey("AdrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adr");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrTemplate", b =>
                {
                    b.HasOne("CADR.Administrations.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrTemplateSection", b =>
                {
                    b.HasOne("CADR.Adrs.Entities.AdrTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrVote", b =>
                {
                    b.HasOne("CADR.Adrs.Entities.Adr", "Adr")
                        .WithMany("Votes")
                        .HasForeignKey("AdrId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CADR.Administrations.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adr");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CADR.Administrations.Entities.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CADR.Administrations.Entities.User", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.Adr", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Sections");

                    b.Navigation("SourceLinks");

                    b.Navigation("TargetLinks");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrFolder", b =>
                {
                    b.Navigation("Adrs");

                    b.Navigation("ChildFolder");
                });

            modelBuilder.Entity("CADR.Adrs.Entities.AdrTemplate", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
