<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\CADR.Common.Repositories\CADR.Common.Repositories.csproj" />
    <ProjectReference Include="..\CADR.Administrations.Repositories.Contracts\CADR.Administrations.Repositories.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>CADR.Administrations.Services.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
