<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CADR.Adrs.Api</RootNamespace>
    <AssemblyName>CADR.Adrs.Api</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\CADR.Common.Mvc\CADR.Common.Mvc.csproj" />
    <ProjectReference Include="..\CADR.Adrs.Repositories\CADR.Adrs.Repositories.csproj" />
    <ProjectReference Include="..\CADR.Adrs.Services\CADR.Adrs.Services.csproj" />
  </ItemGroup>

</Project>
