<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataAccess\CADR.Context.EntityFrameworkCore\CADR.Context.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\CADR.Adrs.Entities\CADR.Adrs.Entities.csproj" />
  </ItemGroup>

</Project>
