<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataAccess\CADR.Context.Tests\CADR.Context.Tests.csproj" />
    <ProjectReference Include="..\CADR.Administrations.Repositories\CADR.Administrations.Repositories.csproj" />
  </ItemGroup>

</Project>
