<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CADR.Administrations.Services</RootNamespace>
    <AssemblyName>CADR.Administrations.Services</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\CADR.Common.Core\CADR.Common.Core.csproj" />
    <ProjectReference Include="..\CADR.Administrations.Repositories.Contracts\CADR.Administrations.Repositories.Contracts.csproj" />
    <ProjectReference Include="..\CADR.Administrations.Services.Contracts\CADR.Administrations.Services.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="AutoMapper.Extensions.EnumMapping" />
  </ItemGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
